### ISSUE TITLE
SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'

### ISSUE THREAD

**Issue by Towerss** [sindresorhus/merge-streams#18]
Hi guys,

I just updated a package that has @sindresorhus/merge-streams as a dependency, and it started to break some of the CircleCi integrations where we have Node < v18.17.0. We are getting this error:

```
> *********ui@1.0.0 build
> webpack --config ./webpack/webpack.prod.js --stats-children --stats-error-details

[webpack-cli] HookWebpackError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
    at makeWebpackError (/root/project/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /root/project/node_modules/webpack/lib/Compilation.js:3075:12
    at eval (eval at create (/root/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:46:1)
    at /root/project/node_modules/webpack/lib/Compilation.js:511:26
    at /root/project/node_modules/copy-webpack-plugin/dist/index.js:632:13
-- inner error --
file:///root/project/node_modules/@sindresorhus/merge-streams/index.js:2
import {PassThrough as PassThroughStream, getDefaultHighWaterMark} from 'node:stream';
                                          ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
caused by plugins in Compilation.hooks.processAssets
file:///root/project/node_modules/@sindresorhus/merge-streams/index.js:2
import {PassThrough as PassThroughStream, getDefaultHighWaterMark} from 'node:stream';
                                          ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Exited with code exit status 2
```

After updating node to versions greater >= v19.9.0 and v18.17.0 it works, as getDefaultHighWaterMark was introduced in those versions.

We have a few containers running Node 18.14.x to 18.16.1. Version 18.16.1 'Hydrogen' (LTS) is not too old as it was released 2023-06-20.

Just a heads up as I think this change is not 100% backward compatible. Maybe this change should be a major semver update, and a notice of breaking changes and how to upgrade to the new version would be great :)

**Comment by emrekaradag12** [comment]
Hi, I'm having the same problem. solution please.

**Comment by Towerss** [comment]
Hi @emrekaradag12 , a quick solution, if possible, is to update Node to versions >= v19.9.0 and v18.17.0 as getDefaultHighWaterMark was introduced in those versions. Any prior version will lead to this error I think.

**Comment by ehmicky** [comment]
Hi,

This is a duplicate of #16 and #17.

Since its creation, this package has been compatible with:

https://github.com/sindresorhus/merge-streams/blob/40481f887d1d3d37475fabf4562ccf52cce7a1ba/package.json#L20

npm [does not document](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) whether `18` is understood as "at least `18.0.0`" or as "latest `18`".
On one hand, `node-semver` would parse `18` as `18.0.0`.
On the other hand, users should always use the latest minor version of any Node.js major version, and not pin to a specific minor/patch version. This ensures you get any security patch.

Ultimately, I have been following the second interpretation, since this is what @sindresorhus usually uses.
However, considering the confusion this is creating, I have opened #19 to fix this, let's see what @sindresorhus thinks.

**Comment by sindresorhus** [comment]
Generally, you are expected to update patch and minor Node.js versions. They bring important security fixes.

**Comment by Towerss** [comment]
@ehmicky @sindresorhus 

Thank you for your work on this package and the super quick resolution.
